### ISSUE TITLE
UIMA SimpleServer is not compatible with the latest Ruta feature (relation annotation)

### ISSUE THREAD

**Issue by Baytars** [apache/uima-ruta#116]
**Describe the bug**
[SimpleServer](https://uima.apache.org/d/uima-addons-current/SimpleServer/simpleServerUserGuide.html) does not recognize relation annotation as mentioned in [Apache UIMA Ruta™ Guide and Reference](https://uima.apache.org/d/ruta-current/tools.ruta.book.html). It will throw error when recognizing any such annotation.
```
HTTP Status 500 - XML output failed
type Exception report
message XML output failed
description The server encountered an internal error that prevented it from fulfilling this request.
exception
java.lang.RuntimeException: XML output failed
	org.apache.uima.simpleserver.output.ResultConverter.getXMLString(ResultConverter.java:88)
	org.apache.uima.simpleserver.servlet.SimpleServerServlet.transformResult(SimpleServerServlet.java:296)
	org.apache.uima.simpleserver.servlet.SimpleServerServlet.analyze(SimpleServerServlet.java:213)
	org.apache.uima.simpleserver.servlet.SimpleServerServlet.doPost(SimpleServerServlet.java:190)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:643)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
root cause
java.lang.NullPointerException: Cannot invoke "org.apache.uima.simpleserver.output.Result.getResultEntries()" because "result" is null
	org.apache.uima.simpleserver.output.ResultConverter.getXMLString(ResultConverter.java:60)
	org.apache.uima.simpleserver.servlet.SimpleServerServlet.transformResult(SimpleServerServlet.java:296)
	org.apache.uima.simpleserver.servlet.SimpleServerServlet.analyze(SimpleServerServlet.java:213)
	org.apache.uima.simpleserver.servlet.SimpleServerServlet.doPost(SimpleServerServlet.java:190)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:643)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:723) 
```

**To Reproduce**
1. Clone the repo `https://e.coding.net/cvd-bioinformatics/transdifferentiation/reprogramming-uima-tomcat.git` in Eclipse
2. In Eclipse, right click on `pom.xml > Run as > maven install` (Make sure you have installed `M2Eclipse`)
3. Right click on the project root, `Run As > Run on Server` (Make sure you have installed `Eclipse Java EE Developer Tools`,`Eclipse Java Web Developer Tools`,`Eclipse Web Developer Tools`,`Eclipse XML Editors and Tools`,`JST Server Adapters Extensions` and `JST Server Adapters Extensions (Apache Tomcat)`, configured at least one available Tomcat server in Eclipse and add the server runtime into the project classpath.)
4. In the browser, visit `http://localhost:8080/UIMADemo/?mode=form` and enter `Neurog2 is downstream of Pax6`. Click "Submit Query".

**Expected behavior**
The server should return an xml response about the text analysis result instead of error messages.

**Please complete the following information:**
 Versions:
 - OS: Windows 10 Professional (version: 21H2)
 - Eclipse: 2022-06 (4.24.0) (Build id: 20220609-1112)
 - Java: Eclipse Adoptium jdk-17.0.1.12-hotspot
 - Maven: Eclipse Embedded 3.8.4/1.18.3.20220227-1319
 - Apache Tomcat: 6.0.37
 - org.apache.uima.uimaj-core: 3.3.1
 - org.apache.uima.SimpleServer: 2.3.1

**Comment by Baytars** [comment]
@reckart The issue is the replicate of that on [UIMA Jira](https://issues.apache.org/jira/browse/UIMA-6483).

**Comment by reckart** [comment]
Thanks. Unfortunately, it appears that the simple server is swallowing the root exception. In the debugger, I can unearth it:

```
java.lang.IllegalArgumentException: Not able to resolve type: Sentence in script SoMeRutaPear
```

Indeed, I do not find a type `...Sentence` in the type system that is contained in the PEAR.

Note that I had to install a Tomcat 9 to test this. When trying with Tomcat 10, I got a different set of exceptions indicating that the simple server is not compatible with the Servlet API version of Tomcat 10.

**Comment by Baytars** [comment]
> Thanks. Unfortunately, it appears that the simple server is swallowing the root exception. In the debugger, I can unearth it:
> 
> ```
> java.lang.IllegalArgumentException: Not able to resolve type: Sentence in script SoMeRutaPear
> ```
> 
> Indeed, I do not find a type `...Sentence` in the type system that is contained in the PEAR.
> 
> Note that I had to install a Tomcat 9 to test this. When trying with Tomcat 10, I got a different set of exceptions indicating that the simple server is not compatible with the Servlet API version of Tomcat 10.

@reckart Yeah, you are right! My negligence caused this error! After deleting the undefined `Sentence`, the server works fine now! You are so helpful! Thank you!
