### ISSUE TITLE
Unexpected behavior of "+" operator

### ISSUE THREAD

**Issue by Theresa93** [apache/uima-ruta#139]
**Describe the bug**
There seems to be a bug with an expression like
`A (B)+ @C`
(reversing through an expression in brackets with a "+" operator)

**To Reproduce**
Go to https://dopamin.averbis.intern/iruta/notebooks/user/klumpp/Ruta-Bug-23-08-21.ipynb or see screenshots below.

**Expected behavior**
In the example on iRuta above, I would expect `MyAnnotation` on "a".

**Screenshots**
Unexpected behavior:
![image](https://github.com/apache/uima-ruta/assets/30152002/459cc364-4c7c-4489-8de1-768b9dab5c24)

Correct behavior (without brackets):
![image](https://github.com/apache/uima-ruta/assets/30152002/b302d371-410e-4d0a-9cba-62bdbdb650fc)

**Comment by pkluegl** [comment]
Thanks for reporting this problem. It will be fixed in the upcoming release.
